// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDRNDXFbxrSuSjTgf_Tbhm7fxVGno-4g',
    appId: '1:96219241237:android:7e5db56e4a845ac8ebe71c',
    messagingSenderId: '96219241237',
    projectId: 'chattify-679f0',
    storageBucket: 'chattify-679f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5x2hxsSTeewCRyCp7zRjVyOGu_5--ms',
    appId: '1:96219241237:ios:4d2c8e4dfad0a2a9ebe71c',
    messagingSenderId: '96219241237',
    projectId: 'chattify-679f0',
    storageBucket: 'chattify-679f0.firebasestorage.app',
    androidClientId: '96219241237-rbb24r019p146q3o9modk0psit9i8ma9.apps.googleusercontent.com',
    iosClientId: '96219241237-qfb7b1tepkc0fe5msqrf8pcn6etfr1bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattify',
  );

}